version: "2"
services:
  app:
    container_name: notification
    restart: always
    build: .
    ports:
      - "8080:3000"
    links:
      - "mongo"
    environment:
      - MONGO_URL=mongodb://mongo/notification
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URI=redis://redis:6379
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379"